version: '3.7'

services:
  web:
    image: httpd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  app:
    image: httpd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet: